export interface Draw {
    Numer: string,
    Dzien: string,
    Miesiac: string,
    Rok: string,
    L1: string,
    L2: string,
    L3: string,
    L4: string,
    L5: string,
    L6: string,
    L7: string,
    L8: string,
    L9: string,
    L10: string,
    L11: string,
    L12: string,
    L13: string,
    L14: string,
    L15: string,
    L16: string,
    L17: string,
    L18: string,
    L19: string,
    L20: string  
}